// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Change is the payload of events.MailChanged.
 */
export interface Change {
    "kind": ChangeKind;
    "ids": number[] | null;
}

/**
 * ChangeKind describes what happened to messages.
 */
export enum ChangeKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ChangeRead = "read",
    ChangeUnread = "unread",
    ChangeStarred = "starred",
    ChangeUnstarred = "unstarred",
    ChangeDeleted = "deleted",
    ChangeCleared = "cleared",
};
