// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MailService exposes inbox operations to the UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * Delete removes messages.
 */
export function Delete(ids: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(2299547964, ids);
}

/**
 * DeleteAll empties the mailbox.
 */
export function DeleteAll(): $CancellablePromise<void> {
    return $Call.ByID(281749607);
}

/**
 * List returns a page of message summaries, newest first.
 */
export function List(q: domain$0.ListQuery): $CancellablePromise<domain$0.Page> {
    return $Call.ByID(426224039, q);
}

/**
 * Open returns a full message and marks it read.
 */
export function Open(id: number): $CancellablePromise<domain$0.Message | null> {
    return $Call.ByID(1862870627, id);
}

/**
 * SaveAttachment saves an attachment to a location chosen by the user.
 */
export function SaveAttachment(msgID: number, attID: number): $CancellablePromise<string> {
    return $Call.ByID(2668680727, msgID, attID);
}

/**
 * SaveRaw saves the original message as an .eml file chosen by the user.
 * It returns the saved path, or "" if the user cancelled.
 */
export function SaveRaw(id: number): $CancellablePromise<string> {
    return $Call.ByID(1781709812, id);
}

/**
 * SetRead marks messages read or unread.
 */
export function SetRead(ids: number[] | null, read: boolean): $CancellablePromise<void> {
    return $Call.ByID(2903613989, ids, read);
}

/**
 * SetStarred stars or unstars messages.
 */
export function SetStarred(ids: number[] | null, starred: boolean): $CancellablePromise<void> {
    return $Call.ByID(3641559408, ids, starred);
}
