// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as smtpd$0 from "../smtpd/models.js";

/**
 * AppInfo describes the running application for the About screen,
 * diagnostics page and dashboard uptime.
 */
export interface AppInfo {
    "name": string;
    "version": string;
    "commit": string;
    "dev": boolean;
    "portable": boolean;
    "dataDir": string;
    "databasePath": string;
    "logDir": string;
    "logFile": string;

    /**
     * Unix milliseconds
     */
    "startedAt": number;
    "goVersion": string;
    "platform": string;
}

/**
 * SaveResult is returned after saving SMTP settings.
 */
export interface SaveResult {
    "config": settings$0.SMTP;
    "status": smtpd$0.Status;
    "warning": string;
}
