// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppInfo describes the running application for the About screen,
 * diagnostics page and dashboard uptime.
 */
export interface AppInfo {
    "name": string;
    "version": string;
    "commit": string;
    "dev": boolean;
    "portable": boolean;
    "dataDir": string;
    "databasePath": string;
    "logDir": string;
    "logFile": string;

    /**
     * Unix milliseconds
     */
    "startedAt": number;
    "goVersion": string;
    "platform": string;
}
