// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SMTPService controls the SMTP server from the UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as smtpd$0 from "../smtpd/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as testmail$0 from "../testmail/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig returns the saved SMTP settings.
 */
export function GetConfig(): $CancellablePromise<settings$0.SMTP> {
    return $Call.ByID(3558403206);
}

/**
 * GetDefaultConfig returns first-run SMTP settings (for "Reset to defaults").
 */
export function GetDefaultConfig(): $CancellablePromise<settings$0.SMTP> {
    return $Call.ByID(2827372071);
}

/**
 * GetStatus returns the server status.
 */
export function GetStatus(): $CancellablePromise<smtpd$0.Status> {
    return $Call.ByID(2985066858);
}

/**
 * SaveConfig validates and saves settings, restarting the server if it is
 * running so changes apply immediately.
 */
export function SaveConfig(cfg: settings$0.SMTP): $CancellablePromise<$models.SaveResult> {
    return $Call.ByID(1567517803, cfg);
}

/**
 * SendTestEmail sends a message through the running server.
 */
export function SendTestEmail(m: testmail$0.Message): $CancellablePromise<void> {
    return $Call.ByID(4070747566, m);
}

/**
 * Start starts the server with the saved settings.
 */
export function Start(): $CancellablePromise<smtpd$0.Status> {
    return $Call.ByID(2449468848);
}

/**
 * Stop stops the server.
 */
export function Stop(): $CancellablePromise<smtpd$0.Status> {
    return $Call.ByID(2789879604);
}
