// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as domain$0 from "../../../../../localmail/internal/domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as mailbox$0 from "../../../../../localmail/internal/mailbox/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as smtpd$0 from "../../../../../localmail/internal/smtpd/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "mail:changed": mailbox$0.Change;
            "mail:received": domain$0.MessageSummary;
            "smtp:status": smtpd$0.Status;
        }
    }
}
