// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Message is a test email composed in the UI.
 */
export interface Message {
    "from": string;

    /**
     * comma-separated
     */
    "to": string;
    "subject": string;
    "body": string;
    "isHtml": boolean;
}
