// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * State is the lifecycle state of the server.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateStopped = "stopped",
    StateRunning = "running",
    StateError = "error",
};

/**
 * Status is reported to the UI.
 */
export interface Status {
    "state": State;
    "running": boolean;
    "host": string;
    "port": number;
    "error": string;
    "startedAt": string | null;

    /**
     * messages accepted since start
     */
    "received": number;

    /**
     * open SMTP connections
     */
    "activeSessions": number;
}
