// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry is a log record flattened for display in the diagnostics UI.
 */
export interface Entry {
    "seq": number;
    "time": string;
    "level": string;
    "component"?: string;
    "message": string;
    "attrs"?: { [_ in string]?: any } | null;
}
