// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthMode controls SMTP authentication.
 */
export enum AuthMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * AUTH not advertised
     */
    AuthNone = "none",

    /**
     * AUTH advertised, any credentials accepted
     */
    AuthAny = "any",

    /**
     * AUTH required with the configured credentials
     */
    AuthRequired = "required",
};

/**
 * SMTP holds SMTP server settings.
 */
export interface SMTP {
    "host": string;
    "port": number;
    "authMode": AuthMode;
    "username": string;
    "password": string;
    "maxMessageMb": number;
    "maxConnections": number;
    "autoStart": boolean;
}
