// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Address is an email address with an optional display name.
 */
export interface Address {
    "name": string;
    "address": string;
}

/**
 * Attachment describes a MIME part that is a file. Its bytes are not stored
 * separately; they are extracted from the raw message on demand.
 */
export interface Attachment {
    "id": number;
    "partIndex": number;
    "fileName": string;
    "contentType": string;
    "size": number;
    "contentId": string;
    "inline": boolean;
}

/**
 * Header is a single message header, in original order.
 */
export interface Header {
    "name": string;
    "value": string;
}

/**
 * ListQuery selects a page of message summaries, newest first.
 */
export interface ListQuery {
    /**
     * Search is a free-text filter over subject, sender and recipients.
     */
    "search": string;

    /**
     * UnreadOnly restricts results to unread messages.
     */
    "unreadOnly": boolean;

    /**
     * Cursor is the opaque value from a previous page's NextCursor.
     */
    "cursor": string;

    /**
     * Limit is the page size (clamped to 1..200, default 50).
     */
    "limit": number;
}

/**
 * Message is the full detail view of a captured email.
 */
export interface Message {
    "id": number;
    "messageId": string;
    "subject": string;
    "from": Address;
    "to": Address[] | null;
    "snippet": string;
    "receivedAt": string;
    "size": number;
    "attachmentCount": number;
    "hasHtml": boolean;
    "isRead": boolean;
    "isStarred": boolean;
    "cc": Address[] | null;
    "bcc": Address[] | null;
    "replyTo": Address[] | null;
    "envelopeFrom": string;
    "envelopeTo": string[] | null;
    "date": string | null;
    "headers": Header[] | null;
    "text": string;
    "html": string;
    "attachments": Attachment[] | null;
    "parseStatus": ParseStatus;
    "parseErrors": string[] | null;
    "remoteAddr": string;
    "helo": string;
}

/**
 * MessageSummary is the lightweight projection used by the inbox list. It
 * never contains bodies so listing stays fast with large mailboxes.
 */
export interface MessageSummary {
    "id": number;
    "messageId": string;
    "subject": string;
    "from": Address;
    "to": Address[] | null;
    "snippet": string;
    "receivedAt": string;
    "size": number;
    "attachmentCount": number;
    "hasHtml": boolean;
    "isRead": boolean;
    "isStarred": boolean;
}

/**
 * Page is one page of results.
 */
export interface Page {
    "items": MessageSummary[] | null;
    "nextCursor": string;
    "total": number;
    "unread": number;
}

/**
 * ParseStatus records how well a message could be parsed.
 */
export enum ParseStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * parsed cleanly
     */
    ParseOK = "ok",

    /**
     * parsed with recoverable problems
     */
    ParsePartial = "partial",

    /**
     * only the raw source is usable
     */
    ParseFailed = "failed",
};
